"""esquema inicial

Revision ID: 9b7041f3193d
Revises: 
Create Date: 2026-09-09 12:05:38.404706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7041f3193d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('almacenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_almacenes')),
    sa.UniqueConstraint('nombre', name=op.f('uq_almacenes_nombre'))
    )
    op.create_table('insumos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=True),
    sa.Column('unidad_medida', sa.String(length=30), nullable=False),
    sa.Column('codigo_barras', sa.String(length=64), nullable=False),
    sa.Column('precio_angeles', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('precio_otros', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.String(length=160), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_alta', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insumos'))
    )
    with op.batch_alter_table('insumos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insumos_codigo_barras'), ['codigo_barras'], unique=True)
        batch_op.create_index(batch_op.f('ix_insumos_sku'), ['sku'], unique=True)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios'))
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('equipo_medico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('tipo_equipo', sa.String(length=80), nullable=True),
    sa.Column('marca', sa.String(length=80), nullable=True),
    sa.Column('modelo', sa.String(length=80), nullable=True),
    sa.Column('numero_serie', sa.String(length=80), nullable=True),
    sa.Column('codigo_barras', sa.String(length=64), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('empresa_propietaria', sa.String(length=20), nullable=True),
    sa.Column('moi', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('almacen_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion_actual', sa.String(length=160), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_alta', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], name=op.f('fk_equipo_medico_almacen_id_almacenes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipo_medico')),
    sa.UniqueConstraint('numero_serie', name=op.f('uq_equipo_medico_numero_serie'))
    )
    with op.batch_alter_table('equipo_medico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipo_medico_codigo_barras'), ['codigo_barras'], unique=True)

    op.create_table('existencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('almacen_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('apartado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], name=op.f('fk_existencias_almacen_id_almacenes')),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumos.id'], name=op.f('fk_existencias_insumo_id_insumos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_existencias')),
    sa.UniqueConstraint('insumo_id', 'almacen_id', name='uq_existencia_insumo_almacen')
    )
    with op.batch_alter_table('existencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_existencias_almacen_id'), ['almacen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_existencias_insumo_id'), ['insumo_id'], unique=False)

    op.create_table('notas_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=30), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('hospital', sa.String(length=200), nullable=False),
    sa.Column('contacto_nombre', sa.String(length=120), nullable=True),
    sa.Column('contacto_telefono', sa.String(length=40), nullable=True),
    sa.Column('direccion_entrega', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_requerida', sa.Date(), nullable=False),
    sa.Column('fecha_procedimiento', sa.Date(), nullable=True),
    sa.Column('especialidad', sa.String(length=60), nullable=True),
    sa.Column('cirugia', sa.String(length=200), nullable=True),
    sa.Column('doctor', sa.String(length=160), nullable=True),
    sa.Column('verificado_con', sa.String(length=30), nullable=True),
    sa.Column('tipo_paciente', sa.String(length=20), nullable=True),
    sa.Column('metodo_pago', sa.String(length=30), nullable=True),
    sa.Column('ciudad', sa.String(length=120), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('revisado_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_revision', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['revisado_por_id'], ['usuarios.id'], name=op.f('fk_notas_venta_revisado_por_id_usuarios')),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuarios.id'], name=op.f('fk_notas_venta_vendedor_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notas_venta'))
    )
    with op.batch_alter_table('notas_venta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notas_venta_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_notas_venta_fecha_creacion'), ['fecha_creacion'], unique=False)
        batch_op.create_index(batch_op.f('ix_notas_venta_folio'), ['folio'], unique=True)

    op.create_table('detalle_nota_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota_venta_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('descripcion_snapshot', sa.String(length=200), nullable=True),
    sa.Column('unidad_snapshot', sa.String(length=30), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['nota_venta_id'], ['notas_venta.id'], name=op.f('fk_detalle_nota_venta_nota_venta_id_notas_venta')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detalle_nota_venta'))
    )
    with op.batch_alter_table('detalle_nota_venta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detalle_nota_venta_nota_venta_id'), ['nota_venta_id'], unique=False)

    op.create_table('entregas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota_venta_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('checklist_almacen_ok', sa.Boolean(), nullable=False),
    sa.Column('fecha_checklist_almacen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checklist_hospital_ok', sa.Boolean(), nullable=False),
    sa.Column('fecha_checklist_hospital', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_entrega', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recibe_nombre', sa.String(length=120), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_regreso_equipo', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['nota_venta_id'], ['notas_venta.id'], name=op.f('fk_entregas_nota_venta_id_notas_venta')),
    sa.ForeignKeyConstraint(['tecnico_id'], ['usuarios.id'], name=op.f('fk_entregas_tecnico_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entregas')),
    sa.UniqueConstraint('nota_venta_id', name=op.f('uq_entregas_nota_venta_id'))
    )
    op.create_table('historial_movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_tipo', sa.String(length=10), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('movimiento', sa.String(length=30), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('saldo_anterior', sa.Integer(), nullable=True),
    sa.Column('saldo_nuevo', sa.Integer(), nullable=True),
    sa.Column('almacen_origen_id', sa.Integer(), nullable=True),
    sa.Column('almacen_destino_id', sa.Integer(), nullable=True),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('importe', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('proveedor', sa.String(length=160), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nota_venta_id', sa.Integer(), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['almacen_destino_id'], ['almacenes.id'], name=op.f('fk_historial_movimientos_almacen_destino_id_almacenes')),
    sa.ForeignKeyConstraint(['almacen_origen_id'], ['almacenes.id'], name=op.f('fk_historial_movimientos_almacen_origen_id_almacenes')),
    sa.ForeignKeyConstraint(['nota_venta_id'], ['notas_venta.id'], name=op.f('fk_historial_movimientos_nota_venta_id_notas_venta')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_historial_movimientos_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_historial_movimientos'))
    )
    with op.batch_alter_table('historial_movimientos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historial_movimientos_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_historial_movimientos_item_id'), ['item_id'], unique=False)

    op.create_table('remisiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=30), nullable=False),
    sa.Column('nota_venta_id', sa.Integer(), nullable=False),
    sa.Column('generado_por_id', sa.Integer(), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('razon_social', sa.String(length=120), nullable=True),
    sa.Column('rfc', sa.String(length=20), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('iva', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cancelada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['generado_por_id'], ['usuarios.id'], name=op.f('fk_remisiones_generado_por_id_usuarios')),
    sa.ForeignKeyConstraint(['nota_venta_id'], ['notas_venta.id'], name=op.f('fk_remisiones_nota_venta_id_notas_venta')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remisiones')),
    sa.UniqueConstraint('nota_venta_id', 'tipo', name='uq_remision_nota_tipo')
    )
    with op.batch_alter_table('remisiones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remisiones_folio'), ['folio'], unique=True)
        batch_op.create_index(batch_op.f('ix_remisiones_nota_venta_id'), ['nota_venta_id'], unique=False)

    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrega_id', sa.Integer(), nullable=False),
    sa.Column('detalle_id', sa.Integer(), nullable=False),
    sa.Column('etapa', sa.String(length=20), nullable=False),
    sa.Column('verificado', sa.Boolean(), nullable=False),
    sa.Column('codigo_escaneado', sa.String(length=64), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['detalle_id'], ['detalle_nota_venta.id'], name=op.f('fk_checklist_items_detalle_id_detalle_nota_venta')),
    sa.ForeignKeyConstraint(['entrega_id'], ['entregas.id'], name=op.f('fk_checklist_items_entrega_id_entregas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklist_items'))
    )
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_items_entrega_id'), ['entrega_id'], unique=False)

    op.create_table('responsivas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=30), nullable=False),
    sa.Column('entrega_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('emitida_por_id', sa.Integer(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=False),
    sa.Column('empresa_propietaria', sa.String(length=20), nullable=True),
    sa.Column('valor_reposicion', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('responsable_custodia', sa.String(length=160), nullable=True),
    sa.Column('paciente_folio', sa.String(length=120), nullable=True),
    sa.Column('accesorios', sa.Text(), nullable=True),
    sa.Column('checklist_salida', sa.Text(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('fecha_devolucion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['emitida_por_id'], ['usuarios.id'], name=op.f('fk_responsivas_emitida_por_id_usuarios')),
    sa.ForeignKeyConstraint(['entrega_id'], ['entregas.id'], name=op.f('fk_responsivas_entrega_id_entregas')),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipo_medico.id'], name=op.f('fk_responsivas_equipo_id_equipo_medico')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_responsivas'))
    )
    with op.batch_alter_table('responsivas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_responsivas_entrega_id'), ['entrega_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_responsivas_equipo_id'), ['equipo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_responsivas_folio'), ['folio'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responsivas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responsivas_folio'))
        batch_op.drop_index(batch_op.f('ix_responsivas_equipo_id'))
        batch_op.drop_index(batch_op.f('ix_responsivas_entrega_id'))

    op.drop_table('responsivas')
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_items_entrega_id'))

    op.drop_table('checklist_items')
    with op.batch_alter_table('remisiones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remisiones_nota_venta_id'))
        batch_op.drop_index(batch_op.f('ix_remisiones_folio'))

    op.drop_table('remisiones')
    with op.batch_alter_table('historial_movimientos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historial_movimientos_item_id'))
        batch_op.drop_index(batch_op.f('ix_historial_movimientos_fecha'))

    op.drop_table('historial_movimientos')
    op.drop_table('entregas')
    with op.batch_alter_table('detalle_nota_venta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detalle_nota_venta_nota_venta_id'))

    op.drop_table('detalle_nota_venta')
    with op.batch_alter_table('notas_venta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notas_venta_folio'))
        batch_op.drop_index(batch_op.f('ix_notas_venta_fecha_creacion'))
        batch_op.drop_index(batch_op.f('ix_notas_venta_estado'))

    op.drop_table('notas_venta')
    with op.batch_alter_table('existencias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_existencias_insumo_id'))
        batch_op.drop_index(batch_op.f('ix_existencias_almacen_id'))

    op.drop_table('existencias')
    with op.batch_alter_table('equipo_medico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipo_medico_codigo_barras'))

    op.drop_table('equipo_medico')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('insumos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insumos_sku'))
        batch_op.drop_index(batch_op.f('ix_insumos_codigo_barras'))

    op.drop_table('insumos')
    op.drop_table('almacenes')
    # ### end Alembic commands ###
