"""precio propuesto por el vendedor, opcional

Revision ID: b4429ada1f8e
Revises: e6e1180442d7
Create Date: 2026-09-09 12:38:17.085380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4429ada1f8e'
down_revision = 'e6e1180442d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_nota_venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_sugerido', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_nota_venta', schema=None) as batch_op:
        batch_op.drop_column('precio_sugerido')

    # ### end Alembic commands ###
