"""hospitales como catalogo y tarifario de renta por hospital

Revision ID: e6e1180442d7
Revises: 9b7041f3193d
Create Date: 2026-09-09 12:30:38.631327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e1180442d7'
down_revision = '9b7041f3193d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('ciudad', sa.String(length=120), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('empresa', sa.String(length=20), nullable=False),
    sa.Column('contacto_nombre', sa.String(length=120), nullable=True),
    sa.Column('contacto_telefono', sa.String(length=40), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hospitales')),
    sa.UniqueConstraint('nombre', name=op.f('uq_hospitales_nombre'))
    )
    op.create_table('tarifas_equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('precio_renta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipo_medico.id'], name=op.f('fk_tarifas_equipo_equipo_id_equipo_medico')),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitales.id'], name=op.f('fk_tarifas_equipo_hospital_id_hospitales')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tarifas_equipo')),
    sa.UniqueConstraint('equipo_id', 'hospital_id', 'vigente_desde', name='uq_tarifa_equipo_hospital_desde')
    )
    with op.batch_alter_table('tarifas_equipo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tarifas_equipo_equipo_id'), ['equipo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tarifas_equipo_hospital_id'), ['hospital_id'], unique=False)

    with op.batch_alter_table('insumos', schema=None) as batch_op:
        batch_op.drop_column('precio_angeles')
        batch_op.drop_column('precio_otros')

    with op.batch_alter_table('notas_venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_notas_venta_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_notas_venta_hospital_id_hospitales'), 'hospitales', ['hospital_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notas_venta', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notas_venta_hospital_id_hospitales'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_notas_venta_hospital_id'))
        batch_op.drop_column('hospital_id')

    with op.batch_alter_table('insumos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_otros', sa.NUMERIC(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('precio_angeles', sa.NUMERIC(precision=12, scale=2), nullable=True))

    with op.batch_alter_table('tarifas_equipo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarifas_equipo_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_tarifas_equipo_equipo_id'))

    op.drop_table('tarifas_equipo')
    op.drop_table('hospitales')
    # ### end Alembic commands ###
